[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
    "gitpython>=2.1.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/test.py"
test-skip = "*universal2:arm64"

[tool.ruff]
extend-select = [
  "B",   # flake8-bugbear
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
]
extend-ignore = [
  "E501",   # Line too long
]
target-version = "py37"

[project]
name = "pymurtree"
version = "0.0.1"
dependencies =[
    "pandas>=1.0.0",
    "numpy>=1.18.0",
]

# [project.dynamic]
# description = 'Python wrapper for the MurTree project'
# authors = 'Jose Urra and Yasel Quintero'

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent", ]

[project.optional-dependencies]
dev = [
    "pytest>=5.3.0",
    "pytest-cov>=2.8.0",
]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src/pymurtree",
]

[project.urls]
