name: Run Tests

on: 
  push:
    branches: ['*']
  pull_request:
    branches: ['develop', 'main']

jobs:
  test_ubuntu:
    name: Run Tests for Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y g++-10

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install . 
          pip install pytest

      - name: Run tests
        run: pytest
  test_windows:
    name: Run Tests on Windows
    runs-on: windows-latest  # Use GitHub-hosted runner for Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # - name: Install dependencies
      #   run: |
      #     pip install . 
      #     pip install pytest

      - name: Install package
        run: |  
          python -m pip install --upgrade pip
          python -m pip install .
 
      # - name: Add Python to PATH
      #   run: |
      #     echo "::add-path::C:\path\to\python"
      #     echo "::add-path::C:\path\to\python\Scripts"

      - name: Run tests
        run: pytest

  test_macos:
    name: Run Tests on macOS
    runs-on: macos-latest  # Use GitHub-hosted runner for macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install . 
          pip install pytest

      - name: Install GCC for C++14 on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc@10

      - name: Run tests
        run: pytest
