# This workflow, labeled "Wheels", is focused on building and distributing Python packages. 
# Specifically, it builds source distributions (sdist) and binary wheel distributions, 
# and uploads them to the Python Package Index (PyPI) when a new release is published on GitHub.
name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build SDist0
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, 
            #  windows-latest, 
            #  macos-latest
            ]

    steps:
    - uses: actions/checkout@v3

    - uses: pypa/cibuildwheel@v2.14
      env:
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_PRERELEASE_PYTHONS: true

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v4
      name: Set up Python 3.x
      with:
        python-version: "3.8"

    - uses: actions/download-artifact@v3
      name: Download wheels
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
      name: Publish to PyPI
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository-url: https://test.pypi.org/legacy/
